# Generated by Django 6.0.3 on 2026-03-21 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок заметки', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
